# Generated by Django 5.0.3 on 2024-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Equipment', 'Equipment'), ('Supplements', 'Supplements')]),
        ),
    ]
