# Generated by Django 5.0.3 on 2024-03-25 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('content', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('article_photo', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Muscle Army'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
