# Generated by Django 5.0.3 on 2024-03-25 17:44

import SoftUniProjectMuscleArmy.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_article_photo_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_photo',
            field=models.ImageField(upload_to='mediafiles/article_photos/', validators=[SoftUniProjectMuscleArmy.articles.validators.validate_file_less_than_5_mb]),
        ),
    ]
