# Generated by Django 5.0.3 on 2024-04-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_slug_article_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_slug',
            new_name='slug',
        ),
    ]
