# Generated by Django 5.0.3 on 2024-04-07 16:19

import SoftUniProjectMuscleArmy.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_article_slug_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_photo',
            field=models.URLField(validators=[SoftUniProjectMuscleArmy.articles.validators.validate_file_less_than_5_mb]),
        ),
    ]
