# Generated by Django 5.0.3 on 2024-04-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_articlecomment_user_commentlike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
    ]
