# Generated by Django 5.0.3 on 2024-04-13 14:23

import SoftUniProjectMuscleArmy.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), SoftUniProjectMuscleArmy.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), SoftUniProjectMuscleArmy.core.validators.validate_only_letters]),
        ),
    ]
