# Generated by Django 5.0.3 on 2024-04-18 17:48

import SoftUniProjectMuscleArmy.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(default='1', upload_to='mediafiles/profile_pictures/', validators=[SoftUniProjectMuscleArmy.core.validators.validate_file_less_than_5mb]),
            preserve_default=False,
        ),
    ]
