# Generated by Django 5.0.3 on 2024-04-18 18:07

import SoftUniProjectMuscleArmy.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), SoftUniProjectMuscleArmy.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), SoftUniProjectMuscleArmy.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/profile_pictures/', validators=[SoftUniProjectMuscleArmy.core.validators.validate_file_less_than_5mb]),
        ),
    ]
